# Numpy Tutorial.

## Importing numpy.

In [0]:
import numpy as np

## Creating an ndarray from a list.

In [11]:
a = np.array([i for i in range(50)], dtype=np.int)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


## ndarray properties.

In [12]:
print(a)
print('a.ndim: ' + str(a.ndim))
print('a.shape: ' + str(a.shape))
print('a.dtype: ' + str(a.dtype))
print('a.size: ' + str(a.size))
print('type(a): ' + str(type(a)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
a.ndim: 1
a.shape: (50,)
a.dtype: int64
a.size: 50
type(a): <type 'numpy.ndarray'>


## Ascending numbers.

In [13]:
a = np.arange(50)
b = np.arange(20, 100, 10)

print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[20 30 40 50 60 70 80 90]


## Reshape.

In [14]:
a = np.arange(50)
a = a.reshape(5, 10)
b = a.ravel()

print(a)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


## Numerical Operations.

In [15]:
b = np.arange(50) * 2
b = b.reshape(5, 10)

c = a + b

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]
[[  0   3   6   9  12  15  18  21  24  27]
 [ 30  33  36  39  42  45  48  51  54  57]
 [ 60  63  66  69  72  75  78  81  84  87]
 [ 90  93  96  99 102 105 108 111 114 117]
 [120 123 126 129 132 135 138 141 144 147]]


In [16]:
b = (np.arange(50, dtype=np.float) + 1) * 2
b = b.reshape(5, 10)

c = b / (a + 1)

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
 [ 22.  24.  26.  28.  30.  32.  34.  36.  38.  40.]
 [ 42.  44.  46.  48.  50.  52.  54.  56.  58.  60.]
 [ 62.  64.  66.  68.  70.  72.  74.  76.  78.  80.]
 [ 82.  84.  86.  88.  90.  92.  94.  96.  98. 100.]]
[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


## Indexing.

In [17]:
a = a.reshape(5, 10)

b = a[0:2, 0:2]
c = a[1:4, 2:8]

print(a)
print(b)
print(c)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[ 0  1]
 [10 11]]
[[12 13 14 15 16 17]
 [22 23 24 25 26 27]
 [32 33 34 35 36 37]]


## Array of Zeros or Ones.

In [18]:
ones = np.ones((2, 3, 3))
zeros = np.zeros((2, 3, 3))

print(ones)
print(zeros)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Linear Spaces.

In [19]:
ls = np.linspace(0, 2, 10)

print(ls)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


## Random numbers.

In [23]:
integer = np.random.randint(0, 5)
uniform = np.random.random((5 , 5))
normal = np.random.randn(5 ,5)

#print(integer)
print(uniform)
print(normal)

[[0.34770118 0.77632026 0.15005423 0.57859767 0.50603177]
 [0.51563581 0.16859876 0.5427395  0.90267922 0.51122391]
 [0.65819064 0.22354747 0.02342209 0.64518791 0.66419986]
 [0.60021623 0.17838978 0.80304798 0.99926424 0.8877316 ]
 [0.59707706 0.59438634 0.34569167 0.77778079 0.83655796]]
[[ 0.24734206  1.05824384  1.28441128  0.13804729 -0.23977901]
 [-1.2257591  -1.17613142 -0.86966661  0.76376001 -1.77975338]
 [-0.96703873 -0.34685277 -1.20405904 -0.89266327  1.82162398]
 [ 0.43262699 -1.77443063 -0.85298288 -0.31721566 -0.43668856]
 [-0.18341306  0.05373925 -1.41783918  0.94341519 -0.03814272]]


## Comparisons.

In [25]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[0, 2, 0], [4, 0, 6]])

arr3 = arr1 == arr2
arr4 = arr1 != arr2
arr5 = arr1 > arr2
arr6 = arr1 < 2

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)
print(arr6)

[[1 2 3]
 [4 5 6]]
[[0 2 0]
 [4 0 6]]
[[False  True False]
 [ True False  True]]
[[ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True False]]
[[ True False False]
 [False False False]]


## Aggregate Functions.

In [26]:
a = np.arange(50, dtype=np.int).reshape(5, 10)

print(a)
print('sum ', a.sum())
print('min ', a.min())
print('max ', a.max())
print('mean ', a.mean())
print('std ', np.std(a))
print('cumsum ', a.cumsum())
print('median ', np.median(a))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
('sum ', 1225)
('min ', 0)
('max ', 49)
('mean ', 24.5)
('std ', 14.430869689661812)
('cumsum ', array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225]))
('median ', 24.5)


## Sorting.

In [27]:
r = np.random.random((5, 5))

print(r)
print('sort ', np.sort(r))
print('sort ax 0 ', np.sort(r, axis=0))
print('sort ax 1 ', np.sort(r, axis=1))

[[0.13557178 0.63103364 0.65831555 0.4445228  0.97613642]
 [0.12177679 0.2608143  0.24875277 0.90679488 0.39746372]
 [0.05489791 0.97414524 0.3613181  0.11363636 0.54672745]
 [0.37356076 0.9135328  0.73772987 0.5459014  0.5868945 ]
 [0.13497177 0.79747051 0.75103514 0.88540146 0.73467224]]
('sort ', array([[0.13557178, 0.4445228 , 0.63103364, 0.65831555, 0.97613642],
       [0.12177679, 0.24875277, 0.2608143 , 0.39746372, 0.90679488],
       [0.05489791, 0.11363636, 0.3613181 , 0.54672745, 0.97414524],
       [0.37356076, 0.5459014 , 0.5868945 , 0.73772987, 0.9135328 ],
       [0.13497177, 0.73467224, 0.75103514, 0.79747051, 0.88540146]]))
('sort ax 0 ', array([[0.05489791, 0.2608143 , 0.24875277, 0.11363636, 0.39746372],
       [0.12177679, 0.63103364, 0.3613181 , 0.4445228 , 0.54672745],
       [0.13497177, 0.79747051, 0.65831555, 0.5459014 , 0.5868945 ],
       [0.13557178, 0.9135328 , 0.73772987, 0.88540146, 0.73467224],
       [0.37356076, 0.97414524, 0.75103514, 0.90679488, 0.976

## Boolean Indexing.

In [28]:
a = np.arange(50, dtype=np.float).reshape(5, 10)
print(a)

a[a > 20] = -1
print(a)

a[a == 15] = -1000
print(a)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]]
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [20. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
[[    0.     1.     2.     3.     4.     5.     6.     7.     8.     9.]
 [   10.    11.    12.    13.    14. -1000.    16.    17.    18.    19.]
 [   20.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]
 [   -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.    -1.]]
