# Tensors


A $torch.Tensor$ is a multi-dimensional matrix containing elements of a single data type. More information on tensors can be found in <https://pytorch.org/docs/stable/tensors.html>.

In [1]:
import torch

import torch.nn as nn

print('###')
tns = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(tns.size())
print(tns)

print('###')
tns = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(tns.size())
print(tns)

print('###')
tns = torch.LongTensor([[1, 2, 3], [4, 5, 6]])
print(tns.size())
print(tns)

print('###')
tns = torch.ByteTensor([[0, 0, 1], [1, 0, 0]])
print(tns.size())
print(tns)

print('###')
tns = torch.IntTensor([[1, 2, 3], [4, 5, 6]])
print(tns.size())
print(tns)

print('###')
tns = torch.DoubleTensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(tns.size())
print(tns)

###
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
###
torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
###
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
###
torch.Size([2, 3])
tensor([[0, 0, 1],
        [1, 0, 0]], dtype=torch.uint8)
###
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
###
torch.Size([2, 2, 3])
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=torch.float64)


## Indexing

In [2]:
print('size: ', tns.size())

print('tns: ', tns)

print('tns[0, 1, 1]: ', tns[0, 1, 1])
tns[0, 1, 1] = 20
print('tns[0, 1, 1]: ', tns[0, 1, 1])
print('tns[0, :, 1]: ', tns[:, 1, 1])

print('tns[0, 1, 1] > 10: ', (tns[0, 1, 1] > 10))
print('tns[0, 1, 1].item() > 10: ', (tns[0, 1, 1].item() > 10))

size:  torch.Size([2, 2, 3])
tns:  tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=torch.float64)
tns[0, 1, 1]:  tensor(5., dtype=torch.float64)
tns[0, 1, 1]:  tensor(20., dtype=torch.float64)
tns[0, :, 1]:  tensor([20., 11.], dtype=torch.float64)
tns[0, 1, 1] > 10:  tensor(True)
tns[0, 1, 1].item() > 10:  True


## Other tensor creation methods

$torch.from\_numpy()$ -> Creates a tensor based on an ndarray.

$torch.ones()$ -> Creates a tensor filled with ones.

$torch.zeros()$ -> Creates a tensor filled with zeros.

In [3]:
import numpy as np

arr = np.array([[1, 2, 4], [8, 16, 32]])
np_tns = torch.from_numpy(arr)

ones = torch.ones((4, 5))
zeros = torch.zeros((4, 5))

print('arr: ', arr)
print('tns: ', np_tns)

print('ones: ', ones)
print('zeros: ', zeros)

arr:  [[ 1  2  4]
 [ 8 16 32]]
tns:  tensor([[ 1,  2,  4],
        [ 8, 16, 32]])
ones:  tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
zeros:  tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


## GPU
Casting a tensor $tns$ to a GPU requires only calling: $tns.cuda()$. If a specific GPU is required, the method $tns.to()$ should be used.

In [4]:
torch.ones([2, 4]).cuda()

cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

## Automatic Differentiation
The parameter $requires\_grad$ controls if a tensor is intended to be used to compute gradients in backpropagation or not.

In [5]:
tns = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = tns.pow(2).sum()
out.backward()
print(tns)
print(tns.grad)

tensor([[ 1., -1.],
        [ 1.,  1.]], requires_grad=True)
tensor([[ 2., -2.],
        [ 2.,  2.]])
